name: nxf-fastqc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - parallel
  - seqkit=0.13.2
  - fastp=0.20.1
  #- multiqc=1.7 get latest from github
  - jq=1.6
  - r-base=4.0.2
  - bioconductor-seqtools=1.22.0 # for ilnm reads
  #- bioconductor-biostrings=2.56.0 # for ont reads
  - r-dt=0.16
  - r-writexl=1.3.1
  - r-kableextra=1.2.1
  - r-rmarkdown=2.3
  - r-knitr=1.29
  - r-dplyr=1.0.2
  - r-rcpproll=0.3.0